---
# tasks file for jmeter-testrun

- name: remove old results.csv
  file:
    path: /tmp/results.csv
    state: absent

- name: template the test_plan
  template:
    src: "jmx_base.jmx.j2"
    dest: "/tmp/jmx_base.jmx"

- name: template the properties file
  template:
    src: "user.properties.j2"
    dest: "/tmp/user.properties"

- name: run jmeter
  command: "{{ jmeter_executable }} -n -t /tmp/jmx_base.jmx -p /tmp/user.properties -l /tmp/results.csv"
  environment:
    JVM_ARGS: -Xmx4g
  notify: Restart logstash
