---
# tasks file for jmeter

- name: update the apt cache (apt-get update)
  apt: update_cache=yes
  become: yes
  become_method: sudo

- name: download default jre
  apt:
    name: default-jre
    state: present
  become: yes
  become_method: sudo

- name: download jmeter
  unarchive:
    src: "{{ jmeter_src }}"
    dest: "{{ jmeter_get_url_dest }}"
    copy: no

- name: unpack jmeter
  unarchive:
    src: "{{ jmeter_get_url_dest }}"
    dest: "{{ jmeter_unarchive_dest }}"
    copy: no
