---
# defaults file for jmeter
jmeter_version: 2.13
jmeter_file_base: "apache-jmeter-{{ jmeter_version }}"
jmeter_file: "{{ jmeter_file_base }}.tgz"
jmeter_src: "http://www.gtlib.gatech.edu/pub/apache//jmeter/binaries/{{ jmeter_file }}"
jmeter_get_url_dest: "/tmp"
jmeter_get_url_dest_file: "{{ jmeter_get_url_dest }}/{{ jmeter_file }}"
jmeter_unarchive_dest: "/tmp"
jmeter_root: "{{ jmeter_dest }}/{{ jmeter_file_base }}"
