---
# defaults file for azure-cluster
cluster_size: 1

# Unfortunatley, I have a variable here for the username but it can't be
# substituted because its in this file
admin_username: "azureadmin"
admin_password: "admin1234!@#$"

region: "Central US"

virtual_machine_size_type: "Basic_A0"
image_publisher: "Canonical"
image_offer: "UbuntuServer"
image_sku: "15.04"
image_version: "15.04.201508180"

group_name: "{{ basename }}"
storage_name: "{{ basename }}"
virtual_network_name: "{{ basename }}-vnet"
subnet_name: "{{ basename }}-subnet"
# It turns out that this wasn't needed (I was facing another bug)
# However, it would be a neat feature to implement!
network_security_group_name: "{{ basename }}-network-security-group"
security_rules:
- somerule to do later
os_disk_name: "{{ basename }}-{{ item }}-os-disk"
network_interface_name: "{{ basename }}-{{ item }}-net-interface"
public_ip_name: "{{ basename }}-{{ item }}-ip"
vm_name: "{{ basename }}-{{ item }}-vm"
computer_name: "{{ basename }}-{{ item }}-computer"
