---
- hosts: "{{ jmeter_group }}"
  remote_user: "{{ admin_username }}"
  vars_files:
  - extra_vars/shared.yml
  roles:
  - role: logstash
    elk_logstash:
      version: 2.1
      pid_file: /var/run/logstash.pid
      patterns: [] # optional; follows same format as `configs`
      configs:
      - src: 5-jmeter-results.conf
        dest: 5-jmeter-results.conf
    sudo: yes
  - jmeter
