---
- hosts: "{{ jmeter_group }}"
  remote_user: "{{ admin_username }}"
  vars_files:
  - extra_vars/shared.yml
  roles:
  - role: jmeter-testrun
    jmeter_executable: /opt/apache-jmeter-2.13/bin/jmeter
    test_plan:
      name: MyTestPlan
      variables:
      - name: MYNAME
        value: MYVALUE
      tree:
      - type: ThreadGroup
        name: MYTHREADGROUP
        main_controller:
          continue_forever: false
          # loops: 150
          loops: 20
        # num_threads: 30
        num_threads: 9
        ramp_time: 60
        tree:
        - type: HTTPSamplerProxy
          name: ZOOKEEPERREST
          domain: myzookeeper-1-ip.centralus.cloudapp.azure.com
          port: 9998
          protocol: http
          path: /znodes/v1/?op=create&amp;name=request-${__threadNum}&amp;dataformat=utf8
          method: POST
          postBodyRaw: true
          encodeBody: false
          body: data-${__threadNum}
          follow_redirects: true
          auto_redirects: false
          use_keepalive: true
          DO_MULTIPAT_POST: false
          monitor: false
          tree:
          - type: HeaderManager
            name: RESTHEADERMANAGER
            headers:
            - name: Content-Type
              value: application/octet-stream
        - type: HTTPSamplerProxy
          name: ZOOKEEPERREST
          domain: myzookeeper-1-ip.centralus.cloudapp.azure.com
          port: 9998
          protocol: http
          path: /znodes/v1/request-${__threadNum}
          method: DELETE
          postBodyRaw: false
          follow_redirects: true
          auto_redirects: false
          use_keepalive: true
          DO_MULTIPAT_POST: false
          monitor: false
          tree:
          - type: HeaderManager
            name: RESTHEADERMANAGER
            headers:
            - name: Content-Type
              value: application/octet-stream
