---
- hosts: "{{ jmeter_group }}"
  remote_user: "{{ admin_username }}"
  vars_files:
  - extra_vars/shared.yml
  roles:
  - role: jmeter-testrun
    jmeter_executable: /opt/apache-jmeter-2.13/bin/jmeter
    test_plan:
      name: MyTestPlan
      variables:
      - name: MYNAME
        value: MYVALUE
      tree:
      - type: ThreadGroup
        name: MYTHREADGROUP
        main_controller:
          continue_forever: false
          loops: 10
        num_threads: 10
        ramp_time: 10
        tree:
        - type: HTTPSamplerProxy
          name: ZOOKEEPERREST
          domain: myzookeeper-1-ip.centralus.cloudapp.azure.com
          port: 9998
          protocol: http
          path: /znodes/v1/
          method: GET
          follow_redirects: true
          auto_redirects: false
          use_keepalive: true
          DO_MULTIPAT_POST: false
          monitor: false
