---
- hosts: localhost
  connection: local
  vars:
    cluster_size: 1
    basename: "myclimachine"
    admin_username: "azureadmin"
    admin_password: "admin1234!@#$"
    region: "Central US"
    virtual_machine_size_type: "Basic_A0"
    image_publisher: "Canonical"
    image_offer: "UbuntuServer"
    image_sku: "15.04"
    image_version: "15.04.201508180"
  tasks:
  - name: Include Extra Vars
    include_vars: extra_vars/all.yml
  - name: Create a new ZK cluster
    customazure:
      state: "present"
      group_name: "{{ basename }}"
      storage_name: "{{ basename }}"
      virtual_network_name: "{{ basename }}"
      subnet_name: "{{ basename }}"
      network_interface_name: "{{ basename }}-{{ item }}"
      vm_name: "{{ basename }}-{{ item }}"
      os_disk_name: "{{ basename }}"
      public_ip_name: "{{ basename }}-{{ item }}"
      computer_name: "{{ basename }}-{{ item }}"
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      region: "{{ region }}"
      image_publisher: "{{ image_publisher }}"
      image_offer: "{{ image_offer }}"
      image_sku: "{{ image_sku }}"
      image_version: "{{ image_version }}"
      virtual_machine_size_type: "{{ virtual_machine_size_type }}"
      subscription_id: "{{ azure_subscription_id }}"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_client_secret }}"
      oauth_endpoint: "{{ azure_oauth_endpoint }}"
    with_sequence: count={{ cluster_size }}
    register: output
  - name: debug
    debug: var=output
  - name: add hosts to inventory
    add_host: name={{ item.public_ip }} group=azure ansible_ssh_pass=admin1234!@#$
    with_items: output.results

- hosts: azure
  remote_user: "azureadmin"
  tasks:
  - name: whoami
    raw: whoami
    register: output
  - name: debug whoami
    debug: var=output
