---
- hosts: localhost
  connection: local
  tasks:
  - name: Include azure variables
    include_vars: extra_vars/azure_vars.yml
  - name: Include shared variables
    include_vars: extra_vars/shared.yml
  - name: create resource group
    azure-resource-group:
      state: present
      region: "{{ region }}"
      group_name: "{{ group_name }}"
      subscription_id: "{{ azure_subscription_id }}"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_client_secret }}"
      oauth_endpoint: "{{ azure_oauth_endpoint }}"
  - name: create storage account
    azure-storage-account:
      state: present
      region: "{{ region }}"
      group_name: "{{ group_name }}"
      storage_name: "{{ storage_name }}"
      subscription_id: "{{ azure_subscription_id }}"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_client_secret }}"
      oauth_endpoint: "{{ azure_oauth_endpoint }}"
  - name: create a virtual network
    azure-virtual-network:
      group_name: "{{ group_name }}"
      state: "present"
      region: "{{ region }}"
      virtual_network_name: "{{ virtual_network_name }}"
      subnet_name: "{{ subnet_name }}"
      subscription_id: "{{ azure_subscription_id }}"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_client_secret }}"
      oauth_endpoint: "{{ azure_oauth_endpoint }}"
  - name: create a public ip
    azure-ip-address:
      group_name: "{{ group_name }}"
      state: "present"
      region: "{{ region }}"
      public_ip_name: "{{ public_ip_name }}"
      subscription_id: "{{ azure_subscription_id }}"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_client_secret }}"
      oauth_endpoint: "{{ azure_oauth_endpoint }}"
    with_sequence: count="{{ cluster_size }}"
  - name: create a network interface
    azure-network-interface:
      group_name: "{{ group_name }}"
      state: "present"
      region: "{{ region }}"
      virtual_network_name: "{{ virtual_network_name }}"
      subnet_name: "{{ subnet_name }}"
      network_interface_name: "{{ network_interface_name }}"
      public_ip_name: "{{ public_ip_name }}"
      subscription_id: "{{ azure_subscription_id }}"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_client_secret }}"
      oauth_endpoint: "{{ azure_oauth_endpoint }}"
    with_sequence: count="{{ cluster_size }}"
  - name: Create a virtual machine
    azure-virtual-machine:
      group_name: "{{ group_name }}"
      state: "present"
      region: "{{ region }}"
      computer_name: "{{ computer_name }}"
      vm_name: "{{ vm_name }}"
      storage_name: "{{ storage_name }}"
      virtual_network_name: "{{ virtual_network_name }}"
      subnet_name: "{{ subnet_name }}"
      public_ip_name: "{{ public_ip_name }}"
      os_disk_name: "{{ os_disk_name }}"
      virtual_machine_size_type: "{{ virtual_machine_size_type }}"
      network_interface_name: "{{ network_interface_name }}"
      image_offer: "{{ image_offer }}"
      image_version: "{{ image_version }}"
      image_publisher: "{{ image_publisher }}"
      image_sku: "{{ image_sku }}"
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      subscription_id: "{{ azure_subscription_id }}"
      client_id: "{{ azure_client_id }}"
      client_secret: "{{ azure_client_secret }}"
      oauth_endpoint: "{{ azure_oauth_endpoint }}"
    with_sequence: count="{{ cluster_size }}"
  # - name: debug
  #   debug: var=output
  # - name: add hosts to inventory
  #   add_host: name={{ item.public_ip }} group=azure ansible_ssh_pass=admin1234!@#$
  #   with_items: output.results

# - hosts: azure
#   remote_user: "azureadmin"
#   tasks:
#   - name: whoami
#     raw: whoami
#     register: output
#   - name: debug whoami
#     debug: var=output
