---

cluster_group_name: "zookeeper-jmeter"
cluster_virtual_network_name: "{{ cluster_group_name}}-vnet"
cluster_subnet_name: "{{ cluster_group_name }}-subnet"

##
#
# keep in mind that the basename should be unique to the whole world. Think of it like your email.
#
##

zookeeper_cluster_size: 3
zookeeper_basename: "myzookeeper"
zookeeper_group: "zookeeper"

jmeter_cluster_size: 1
jmeter_basename: "myjmeter"
jmeter_group: "jmeter"
